steps:
- name: 'node:20'
  entrypoint: npm
  args: ['install']
- name: 'node:20'
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'clayton-construction-website'
    - '--source'
    - '.'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'